# Generated by Django 2.1.7 on 2019-09-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentum_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentumfiles',
            old_name='magazine_img',
            new_name='file_upload',
        ),
    ]
