# Generated by Django 2.1.7 on 2019-09-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentum_app', '0002_auto_20190916_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentumfiles',
            name='file_upload',
            field=models.FileField(default='', upload_to='upload_files/'),
        ),
    ]
