# Generated by Django 2.1.7 on 2019-09-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentum_app', '0006_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='users',
            new_name='user',
        ),
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
