# Generated by Django 2.1.7 on 2019-09-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentum_app', '0007_auto_20190923_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
