# Generated by Django 2.1.7 on 2019-09-26 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
        ('documentum_app', '0012_auto_20190924_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='company_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Company.Company'),
        ),
    ]
