# Generated by Django 2.1.7 on 2019-10-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentum_app', '0015_post_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
