# Generated by Django 2.1.7 on 2019-10-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentum_app', '0016_auto_20191011_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.CharField(blank=True, max_length=225, unique=True),
        ),
    ]
