# Generated by Django 2.1.7 on 2019-10-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentum_app', '0018_auto_20191011_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.CharField(blank=True, default=1, max_length=225),
            preserve_default=False,
        ),
    ]
